kubectl apply -f azure/angular-app-claim1-persistentvolumeclaim.yaml 
kubectl apply -f azure/angular-app-cm0-configmap.yaml 
kubectl apply -f azure/angular-app-deployment.yaml 
kubectl apply -f azure/angular-app-ingress.yaml 
kubectl apply -f azure/angular-app-service.yaml 
kubectl apply -f azure/conbent-article-api-cm0-configmap.yaml 
kubectl apply -f azure/conbent-article-api-cm1-configmap.yaml 
kubectl apply -f azure/conbent-article-api-deployment.yaml 
kubectl apply -f azure/conbent-identity-api-cm0-configmap.yaml 
kubectl apply -f azure/conbent-identity-api-deployment.yaml 
kubectl apply -f azure/conbent.article.api-service.yaml 
kubectl apply -f azure/conbent.identity.api-service.yaml
kubectl apply -f azure/postgres-data-persistentvolumeclaim.yaml 
kubectl apply -f azure/postgresql-deployment.yaml 
kubectl apply -f azure/postgresql-service.yaml
kubectl apply -f azure/redis-deployment.yaml 
kubectl apply -f azure/redis-service.yaml 
kubectl apply -f azure/storage-persistentvolumeclaim.yaml