<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Debug;Release;Debug Docker;Debug Service;Debug Consonle;Debug Several Services</Configurations>
  </PropertyGroup>

      <ItemGroup>
          <Compile Include="..\..\..\Infrastructure\Shared\ActivityExtensions.cs" Link="Extensions\ActivityExtensions.cs" />
          <Compile Include="..\..\..\Infrastructure\Shared\MigrateDbContextExtensions.cs" Link="Extensions\MigrateDbContextExtensions.cs" />
      </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0-preview.4.24156.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0-preview.2.24128.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Infrastructure\EventBusRabbitMQ\Conbent.EventBusRabbitMQ.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\IntegrationEventLogEF\Conbent.IntegrationEventLogEF.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\ServiceDefaults\Conbent.Service.Defaults.csproj" />
  </ItemGroup>

</Project>
