<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Conbent.EventBusRabbitMQ</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
    <Configurations>Debug;Release;Debug Docker;Debug Service;Debug Consonle;Debug Several Services</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\ActivityExtensions.cs" Link="ActivityExtensions.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.RabbitMQ.Client" Version="8.0.0-preview.2.23619.3" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventBus\Conbent.EventBus.csproj" />
  </ItemGroup>

</Project>